### ISSUE TITLE
transpose rows to column in MDX

### ISSUE THREAD

**Issue by nischal009** [cubewise-code/mdxpy#14]
How to transpose rows to column in MDX . 
Generate MDX output with dimension combination with measure in columns

**Comment by MariusWirtz** [comment]
Hi @nischal009,

I am not sure I understand your first request.
Are you requesting a function on the MdxBuilder class that swaps the rows and columns?
Why not just position it that way in the first place?

I don't quite understand the second request. Please provide more context.

**Comment by nischal009** [comment]
![image](https://user-images.githubusercontent.com/39788662/91976399-81396900-ed3e-11ea-87b1-efd932cdad79.png)
Trying to write MDX to swap rows (highlighted in yellow) to column .
In SQL we can write case function to achieve this .

**Comment by MariusWirtz** [comment]
Hi @nischal009,

needless to say, you can't use mdxpy to query data from Excel.
What is the origin of this data? Does it come from TM1 or another OLAP data source that can be queried through MDX?

You can use mdxpy to build an MDX query with measures on the columns.

So this python code:

``` python
from mdxpy import MdxBuilder, MdxHierarchySet

query = MdxBuilder.from_cube("Sales") \
    .rows_non_empty() \
    .add_hierarchy_set_to_row_axis(MdxHierarchySet.all_members(dimension="Business Unit", hierarchy="Business Unit")) \
    .add_hierarchy_set_to_row_axis(MdxHierarchySet.all_members(dimension="Industry", hierarchy="Industry")) \
    .add_hierarchy_set_to_row_axis(MdxHierarchySet.member("[Customer].[Total Customer]")) \
    .add_hierarchy_set_to_column_axis(MdxHierarchySet.members([
    "[SalesMeasure].[Revenue]",
    "[SalesMeasure].[Gross Margin]",
    "[SalesMeasure].[COGS]"])) \
    .where("[Time].[2018]", "[Version].[Actual]")

mdx = query.to_mdx()
print(mdx)
```

produces this MDX query:

``` SQL
SELECT
{[SALESMEASURE].[SALESMEASURE].[REVENUE],[SALESMEASURE].[SALESMEASURE].[GROSSMARGIN],[SALESMEASURE].[SALESMEASURE].[COGS]} ON 0,
NON EMPTY {[BUSINESSUNIT].[BUSINESSUNIT].MEMBERS} * {[INDUSTRY].[INDUSTRY].MEMBERS} * {[CUSTOMER].[CUSTOMER].[TOTALCUSTOMER]} ON 1
FROM [SALES]
WHERE ([TIME].[TIME].[2018],[VERSION].[VERSION].[ACTUAL])
```

**Comment by nischal009** [comment]
Hi Marius , 
Data is from TM1 only , just for representation i have shown you the excel data .
Thanks for the support . Will check this and get back to you .

**Comment by MariusWirtz** [comment]
Hi @nischal009,

I suggest you use TM1py to retrieve the data.
If you do so, make sure you use the function `execute_mdx_dataframe_shaped`. It retrieves the data in the shape of the MDX query.

``` python
with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL) as tm1:
    df = tm1.cells.execute_mdx_dataframe_shaped(mdx)
```

The `execute_mdx_dataframe` function retrieves the data in a "flat table".

**Comment by nischal009** [comment]
yes, currently we are retrieving into Data frame and changing the format of data required for calculation . 
Thought if we can bring the data through MDX exactly in the format required for calculation , we can optimize the data processing .

**Comment by MariusWirtz** [comment]
Yeah. if you use `execute_mdx_dataframe_shaped` you can don't have to rearrange the data in the data frame. That's a good use case for this function.

**Comment by nischal009** [comment]
I could use  execute_mdx_dataframe() method only . 
df = tm1.cells.execute_mdx_dataframe_shaped(mdx) is giving (AttributeError: 'CellService' object has no attribute 'execute_mdx_dataframe_shaped') also this method tm1.cells.execute_mdx_dataframe_shaped(mdx) is not there in tm1py documentation 1.0.2

**Comment by MariusWirtz** [comment]
You must upgrade to the latest version of TM1py with pip
`pip install tm1py --upgrade`
