### ISSUE TITLE
Support DIMENSION PROPERTIES in mdxpy

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/mdxpy#18]
MDXpy should support DIMENSION PROPERTIES. They are a standard feature of MDX and are supported in TM1. Since TM1 11 they can also be used in MDX datasources for TI.

> Microsoft Reference:

https://docs.microsoft.com/de-de/analysis-services/multidimensional-models/mdx/mdx-member-properties-intrinsic-member-properties?view=asallproducts-allversions

> TM1 sample
```
SELECT 
{[plan_time].[plan_time].[Q1-2004], [plan_time].[plan_time].[Q1-2004].CHILDREN} 
DIMENSION PROPERTIES [plan_time].[Time_Swedish] on 0,
[plan_chart_of_accounts].[plan_chart_of_accounts].MEMBERS 
DIMENSION PROPERTIES MEMBER_NAME on 1
FROM [plan_BudgetPlan]
WHERE ([plan_business_unit].[plan_business_unit].[10110], [plan_department].[plan_department].[105], [plan_source].[plan_source].[input]) 
DIMENSION PROPERTIES MEMBER_NAME, [plan_business_unit].[BusinessUnit_Swedish], [plan_business_unit].[Currency], [plan_department].[Department_Swedish]
```

> More background in IBM Planning Analytics Forum

https://community.ibm.com/community/user/businessanalytics/communities/community-home/digestviewer/viewthread?GroupId=3067&MessageKey=beac9ad9-37cf-403c-9436-5fdb8fac8f87&CommunityKey=8fde0600-e22b-4178-acf5-bf4eda43146b&tab=digestviewer&ReturnUrl=%2fcommunity%2fuser%2fbusinessanalytics%2fcommunities%2fcommunity-home%2fdigestviewer%3fcommunitykey%3d8fde0600-e22b-4178-acf5-bf4eda43146b%26tab%3ddigestviewer

**Comment by macsir** [comment]
Hi, @MariusWirtz 
Just check on this one. Is the enhancement available now for the latest release? Thanks.

**Comment by MariusWirtz** [comment]
Hi @macsir,

sorry for the late reply. 
No. Unfortunately, it's not available yet. please feel free to open a MR.
