### ISSUE TITLE
Is there a way to define an empty set or tuple on axis? 

### ISSUE THREAD

**Issue by headmann** [cubewise-code/mdxpy#21]
Consider following query, returning a view, similar to a traditional "extract" view:
SELECT 
{some tuple} ON ROWS
{} ON COLUMNS
FROM CUBE

**Comment by MariusWirtz** [comment]
Sure. Just write this:

``` python
from mdxpy import MdxBuilder, MdxHierarchySet

query = MdxBuilder.from_cube(cube="c1")
query.add_hierarchy_set_to_column_axis(MdxHierarchySet.all_leaves(
    dimension="d1",
    hierarchy="d1"))
query.add_hierarchy_set_to_column_axis(MdxHierarchySet.tm1_subset_to_set(
    dimension="d2",
    hierarchy="d2",
    subset="Default"))

mdx = query.to_mdx()

print(mdx)
```

It produces this MDX without selection on the rows

```
SELECT
{TM1FILTERBYLEVEL({TM1SUBSETALL([D1].[D1])},0)} * {TM1SUBSETTOSET([D2].[D2],"Default")} ON 0
FROM [C1]
```

MDX requires at least one selection on the columns. All other axes can be empty.

**Comment by headmann** [comment]
Fantastic, thank you for sharing. As a separate question - is there a way to define and use a "extract" (not a stargate) view through the REST API? So the server will not need to ViewConstruct() and will process such view row-by-row (or column-by-column) ?

Thanks
Alex

**Comment by MariusWirtz** [comment]
Not that I know.

To work around this, you can break a large MDX query into multiple smaller ones.

Or you can "create a cell set" (= execute MDX or a view) and retrieve the content through REST/ TM1py in small chunks with the `top`, `skip` arguments. However this still "constructs" the full view in memory on the server-side.

**Comment by headmann** [comment]
> MDX requires at least one selection on the columns. All other axes can be empty.

Actually, it is leading back to my question, consider this query (which works perfectly fine):
SELECT
{} ON 0,
{TM1FILTERBYLEVEL({TM1SUBSETALL([D1].[D1])},0)} * {TM1SUBSETTOSET([D2].[D2],"Default")} ON 1
FROM [C1]

So, I think it might be useful to have an ability to define an explicit "empty tuple" for more flexibility.

Thanks,
Alex.

**Comment by MariusWirtz** [comment]
Ah yes. I didn't think of this.

Please feel free to open an MR for this empty `MdxHierarchySet`

**Comment by headmann** [comment]
Hi Marius - maybe a dumb question, but how do I open the MR?

**Comment by MariusWirtz** [comment]
Hi @headmann,

you need to fork this project. Then do the changes to the code and do all the git stuff (`git add`, `git commit`, `git push`, etc.) and then create an MR (Merge Request) in GitHub.

I don't have a tutorial at hand, but I'm sure you will find a good blog post about it! If you do get stuck on the way feel free to post questions in this thread.

Looking forward to your contribution :)

**Comment by headmann** [comment]
Hi @MariusWirtz - I'll sure give it a try.
