### ISSUE TITLE
Are mdxsets ready to use?

### ISSUE THREAD

**Issue by dmillerksu** [cubewise-code/mdxpy#33]
Is the current master branch ready to use?  Are you planning on releasing soon?  I'd like to start using the MdxSet and cross join features, but figured I'd confirm that it's ready for public use first.

**Comment by dmillerksu** [comment]
I downloaded and installed the current master branch, but I don't think the MdxSet is going to work for what I'm trying to do.  I'm trying to union a bunch of cross joins of multiple dimensions as rows in a view.  I only see the one example of creating a cross join with MdxSet.  I used that, but it appears I can't add that to the rows of an MdxBuilder.  I see there's a cross_join function for MdxHierarchySet, but it's asking for a list of MdxSets, and that still throws the error saying I can't use MdxSets in a hierarchy set.

Is there a better mdxpy approach to this?

Essentially, what I'm trying to build is like this...
SELECT 
{TM1FILTERBYLEVEL({TM1DRILLDOWNMEMBER({[time].[time].[2022]}, ALL, RECURSIVE)},0)} ON 0,
{ {[d1].[d1].[d1elem1]} * {[d2].[d2].[d2elem1]} * {[d3].[d3].[d3elem1]},
{[d1].[d1].[d1elem2]} * {[d2].[d2].[d2elem2]} * {[d3].[d3].[d3elem2]} ,
{[d1].[d1].[d1elem3]} * {[d2].[d2].[d2elem3]} * {[d3].[d3].[d3elem3]} }
ON 1
FROM [cube]

The use case is that finance wants some reports built for executive levels in certain ways that require various pivots and intersections of our income statement cube.  They've been building these reports in Excel, but they want these transferred to our new primary interface, Apliqo UX.  Apliqo provides methods for enabling cross joins, but with the number of different cross joins and subsequent custom calculations, it makes more sense just to build a new cube to handle the reporting.  I built a new cube with a measure dimension that aggregates the various cross join definitions, but the TI process is slow so was hoping to leverage TM1py improve the performance.  I'm hoping I can build a single MDX query to grab all cross joins rather than for each measure.

**Comment by MariusWirtz** [comment]
Thanks for reporting this. Currently, you can do some stuff with the `MdxSet` (see below), but it's not really supported to be used in the `MdxBuilder`. We will finish that work before doing the next release.

``` python

from mdxpy import MdxSet, Member, MdxHierarchySet

from TM1py.Services.TM1Service import TM1Service

mdx_set = MdxSet.cross_joins([
    MdxHierarchySet.children(Member.of("d1", "Total")),
    MdxHierarchySet.members([
        Member.of("d2", "e1"),
        Member.of("d2", "e2")]),
])

with TM1Service(base_url="https://localhost:12354", user="admin", password="apple") as tm1:
    result = tm1.elements.execute_set_mdx(
        mdx=mdx_set.to_mdx(),
        member_properties=["Name"],
        element_properties=None,
        parent_properties=None)

    print(result)

```

I wonder if perhaps the problem could be addressed through tuples. See this example below. Would that solve your problem?

``` python
import mdxpy
from mdxpy import Member, MdxBuilder

mdxpy.Member.SHORT_NOTATION = True

query = MdxBuilder.from_cube("c1")
query = query.add_member_tuple_to_columns(Member.of("d1", "e1"), Member.of("d2", "e4"))
query = query.add_member_tuple_to_columns(Member.of("d1", "e2"), Member.of("d2", "e2"))
query = query.add_member_tuple_to_columns(Member.of("d1", "e2"), Member.of("d2", "e1"))

print(query.to_mdx())

```

```
SELECT
{([d1].[e1],[d2].[e4]),([d1].[e2],[d2].[e2]),([d1].[e2],[d2].[e1])} ON 0
FROM [c1]
```
