### ISSUE TITLE
[Question] How to select multiple elements within the same dimension ?

### ISSUE THREAD

**Issue by Maxpinch** [cubewise-code/mdxpy#47]
Hello,
First of all, good job for this library, it's extremely useful ! My question might be stupid but I cannot find a way to specify multiple element within the same dimension. For example
`.add_hierarchy_set_to_axis(0, MdxHierarchySet.member(Member.of("Region", "US")))`
will return 
`{[region].[region].[us]} DIMENSION PROPERTIES MEMBER_NAME ON 0`

But I want wondering how to return something like
`{[region].[region].[us],[region].[region].[eu]} DIMENSION PROPERTIES MEMBER_NAME ON 0`

Thank you

**Comment by MariusWirtz** [comment]
Here is an example:

``` python
from mdxpy import MdxHierarchySet, Member

MdxHierarchySet.members([Member.of('Region', 'England'), Member.of('Region', 'Wales')])

```
