### ISSUE TITLE
Trailing comma in MDX when rows_non_empty used but no hierarchy_set defined on rows

### ISSUE THREAD

**Issue by tbeare** [cubewise-code/mdxpy#53]
**# Issue**
When "rows_non_empty" is used but no hierarchy set for rows is provided to mdxpy, it generates mdx which is syntactically incorrect causing an error when it is used. After "MEMBER_NAME ON 0" the mdx has a trailing comma before the cube name.

**# Error**
The MDX generated caused the following error when consumed:

"An error occurred: Text: '{"error":{"code":"501","message":"Syntax error at or near: '\r\n\r\nFROM [commercialeventsmain]', character position 636"}}'"

![image](https://github.com/user-attachments/assets/4eb6c718-1b9d-41b7-9603-84bc6d1ebc61)

**# Code**
```
mdx = MdxBuilder.from_cube(cube_name)
mdx.rows_non_empty()
mdx.columns_non_empty()
for dimension in dimensions:
    if dimension != "Year":
        mdx.add_hierarchy_set_to_column_axis(MdxHierarchySet.all_leaves(dimension))
mdx.to_mdx()
```

**# MDX Output**
```
SELECT
NON EMPTY {[year].[year].[2024]} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([week].[week])},0)} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([version].[version])},0)} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([commercialadjustmentlayer].[commercialadjustmentlayer])},0)} *
{TM1FILTERBYLEVEL({TM1SUBSETALL([commercialeventscategory].[commercialeventscategory])},0)} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([commercialeventssection].[commercialeventssection])},0)} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([commercialeventstitle].[commercialeventstitle])},0)} * 
{TM1FILTERBYLEVEL({TM1SUBSETALL([commercialeventsmainmeasure].[commercialeventsmainmeasure])},0)} 
DIMENSION PROPERTIES MEMBER_NAME ON 0,
 
FROM [commercialeventsmain]
```

**# Suggested solution**

This comma should not be added if no hierarchy set for rows is provided, even if rows_non_empty() is specified. I haven't tested it but wonder if the same would happen if columns_non_empty is specified by no hierarchy set for columns provided. Maybe the solution should cover that eventuality as well.

**Comment by MariusWirtz** [comment]
solved
